TOKEN_KEY: TOKEN_KEY
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapping/*.xml

redis:
  host: 127.0.0.1
  port: 6379
  pool:
    MaxTotal: 50
    MaxIdle: 10
    MaxWaitMillis: 1000
    testOnBorrow: true